AZURE_LOCATION: 'westus2'
RESOURCE_NAME_PREFIX: 'devrad'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'devr-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'replace me in repo secrets'
CICD_AGENT_TYPE: 'azuredevops'
CERT_TYPE: 'selfsigned'