AZURE_LOCATION: 'centralus'
RESOURCE_NAME_PREFIX: 'APIM'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'Admin'
CICD_AGENT_TYPE: 'azuredevops'
CERT_TYPE: 'selfsigned'
